In [1]:
import numpy as np
print(np.shape([[[1], [2]], [[3], [4]]]))

(2, 2, 1)


In [11]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)


[[ 0.43489453 -0.89448146 -0.45027045]
 [-0.27063204 -0.0532741  -0.44166162]
 [-0.09728233 -0.18163235 -0.04479485]]
(3, 3)
